config/routes.rb
Rails.application.routes.draw do

  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to:"sessions#destroy"
  post "message", to:"messages#create"

  mount ActionCable.server, at: '/cable'

  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: {minimum:3, maximum:15}, uniqueness: {case_insensitive: false}
  has_many :message
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.includes(:user).all
  end

  def create
    byebug
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.message.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", { mod_message: message_render(message) }
    else
      # handle failure, e.g., render an error message or re-render the form
    end
  end

  private

  def message_params
    params.permit(:body) 
  end

  def message_render(message)
    render(partial: "message", locals: {message: message})
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    # Renders the signup page
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Account created successfully'
      redirect_to root_path
    else
      flash.now[:error] = user.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      # bad scenario
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class="flex flex-col w-full min-h-[90vh]">
  <div class="w-full flex flex-col items-center justify-center py-4">
    <div class="rounded-full border-4 p-2 border-gray-200">
      <%= lucide_icon :coffee, class: 'w-16 h-16 text-orange-500' %>
    </div>
    <h1 class="text-2xl font-medium text-gray-600">Let's Chat</h1>
  </div>
  <div class="flex w-full gap-x-4 grow max-h-[600px]">
    <div class="w-[80%] border-2 shadow-xl p-2 flex flex-col rounded-lg">
      <div class="grow overflow-y-auto" id="message-container">
        <%= render @messages %>
      </div>
      <%= form_with url: message_path, method: :post, html: { class: "flex", data: { remote: true } } do |form| %> 
        <%= form.text_field :body, placeholder: "Chat", id: "chat-message-body", class: "rounded-md w-full" %> 
        <button type="submit" class="px-2"> 
          <%= lucide_icon :send, class: 'w-8 h-8 text-orange-500' %> 
        </button> 
      <% end %>
    </div>
    <div class="w-[20%] border-2 shadow-xl p-2 rounded-lg">
      <div class="text-center font-medium text-xl py-2">Online Members</div>
      <div class="bg-gray-900 rounded-lg overflow-hidden" id="online-members">
        <!-- This will be dynamically populated -->
      </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="flash-message flex justify-between items-center p-4 mb-4 rounded-lg 
              <%= message_type == 'success' ? 'bg-green-200 text-green-800' : '' %>
              <%= message_type == 'error' ? 'bg-red-200 text-red-800' : '' %>">
    <span><%= message_content %></span>
    <button onclick="this.parentElement.style.display='none'" class="ml-4 text-gray-600 hover:text-gray-900">
      <%= lucide_icon :x, class: 'w-8 h-8' %>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="bg-black px-2 py-2">
  <div class="container mx-auto flex justify-between text-white py-1">
    <div>
      <a href="/" class="hover:bg-slate-800 rounded-lg transition-all py-2 px-2"
        >Chatroom</a
      >
      <a href="/" class="hover:bg-slate-800 rounded-lg transition-all py-2 px-2"
        >Messages</a
      >
    </div>
    <div class="relative">
      <a
        id="language-dropdown-toggle"
        href="javascript:void(0);"
        class="hover:bg-slate-800 rounded-lg transition-all py-2 px-2"
        >Account</a
      >
      <div
        id="language-dropdown"
        class="hidden absolute right-0 mt-2 py-2 w-48 bg-white rounded-lg shadow-xl"
      >
        <% if logged_in? %>
          <%# <a href="#" class="block px-4 py-2 text-black hover:bg-gray-200">Log out</a> %>
          <%= link_to "Log out", logout_path, method: :delete, class: "block px-4 py-2 text-black hover:bg-gray-200" %>
        <% else %>
          <%= link_to "Log in", login_path, class: "block px-4 py-2 text-black hover:bg-gray-200" %>
          <a href="#" class="block px-4 py-2 text-black hover:bg-gray-200">Sign up</a>
        <% end %>
      </div>
      <a
        href="/"
        class="bg-blue-500 rounded-lg hover:bg-slate-800 transition-all py-2 px-2"
        >Signup</a
      >
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat Application</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render 'layouts/navigation' %>
      <div class="container mx-auto flex flex-col">
        <%= render "layouts/messages" %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<p>
    <strong class="italic"><%= message.user.username %>:</strong> <%=
        message.body %>
</p>